<?php

namespace CrudBundle\Repository;

/**
 * test33Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class test33Repository extends \Doctrine\ORM\EntityRepository
{
}
